### ISSUE TITLE
Sudgestion: A more profesional call to generate the html code

### ISSUE THREAD

**Issue by DomiiBunn** [AshmaDev/sexymail#1]
Maybe something like `generate` in addition to the pre-existing `ejaculate`

**Comment by AshmaDev** [comment]
The project was created as a humorous demo for my SM. 
I see more and more people are interested, so I'll probably rewrite it into more formal (aka boring) version.

**Comment by DomiiBunn** [comment]
I like the "naughty" aproach. Tho it's not something that would fly in corpo world :(
